baseURL = 'https://example.org/'
languageCode = 'pt-br'
title = 'Wings'
theme = 'wings'

#
# [[menus.main]]
# name = 'Posts'
# pageRef = '/posts'
# weight = 20
#
# [[menus.main]]
# name = 'Notas'
# pageRef = '/notas'
# weight = 30

# [params.author]
#   name = 'Ícaro Chiabai'
#   bio = 'Minhas coisas!'
#   postInfo = 'Apaixonado por coisas belas.'
