import Head from 'next/head'
import styles from '../styles/index.module.css'
import About from './about'
import Experience from './experience'
import PerlinNoise from '@/components/sketch/perlinnoise/perlinnoise'  

        
export default function Home() {
  return (
    <>
      <Head>
        <title>Ícaro Chiabai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.box}>
          <About />
          <Experience />
          <PerlinNoise />
      </main>
    </>
  )
}
